http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  signup:
    host: localhost
    paths: '/signup'
  signin:
    host: localhost
    paths: '/signin'
  signout:
    host: localhost
    paths: '/signout'
  postProject:
    host: localhost
    paths: '/project'
  getProject:
    host: localhost
    paths: '/project'
  getProjectKanban:
    host: localhost
    paths: '/project/kanban'
  getProjectScrum:
    host: localhost
    paths: '/project/scrum'
  getProjectBugtracking:
    host: localhost
    paths: '/project/bugtracking'
  getAllUsers:
    host: localhost
    paths: '/allusers'
  getPriority:
    host: localhost
    paths: '/priority'
  getComponent:
    host: localhost
    paths: '/component'
  postComponent:
    host: localhost
    paths: '/component'
  getIssue:
    host: localhost
    paths: '/issue'
  getLabel:
    host: localhost
    paths: '/label'
  getLinkedIssues:
    host: localhost
    paths: '/linkedissues'
  getSprint:
    host: localhost
    paths: '/sprint'
  postSprint:
    host: localhost
    paths: '/sprint'
  updateSprint:
    host: localhost
    paths: '/sprint'
  postWorkItem:
    host: localhost
    paths: '/workItem'
  getWorkItem:
    host: localhost
    paths: '/workItem'
  updateWorkItem:
    host: localhost
    paths: '/updateWorkItem'
  getWorkItemProject:
    host: localhost
    paths: '/workItemProject'
  getWorkItemEpic:
    host: localhost
    paths: '/workItem/epic'
  getWorkItemById:
    host: localhost
    paths: '/workItemById'
  getIssueEpic:
    host: localhost
    paths: '/issue/epic'
  updateComponent:
    host: localhost
    paths: '/component'
  postComment:
    host: localhost
    paths: '/comment'
  putComment:
    host: localhost
    paths: '/comment'
  changeItemPosition:
    host: localhost
    paths: '/workItemChangePosition'
  changeItemPositionBTSprints:
    host: localhost
    paths: '/workItemChangeSprint'
  changeWorkItemPositionStatus:
    host: localhost
    paths: '/workItemChangePositionStatus'
  changeWorkItemStatus:
    host: localhost
    paths: '/workItemChangeStatus'
  getComponentByProject:
    host: localhost
    paths: '/componentProject'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authSevice:
    url: 'http://localhost:8082'
  projectSevice:
    url: 'http://localhost:8083'
  prioritySevice:
    url: 'http://localhost:8085'
  componentSevice:
    url: 'http://localhost:8087'
  issueSevice:
    url: 'http://localhost:8086'
  labelSevice:
    url: 'http://localhost:8088'
  linkedissuesSevice:
    url: 'http://localhost:8089'
  sprintSevice:
    url: 'http://localhost:8090'
  workItemSevice:
    url: 'http://localhost:8084'
  commentSevice:
    url: 'http://localhost:8091'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  registerPipeline:
    apiEndpoints:
      - signup
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authSevice
              changeOrigin: true

  loginPipeline1:
    apiEndpoints:
      - signin
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authSevice
              changeOrigin: true
  logoutPipeline1:
    apiEndpoints:
      - signout
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authSevice
              changeOrigin: true

  postProjectPipeline:
    apiEndpoints:
      - postProject
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: projectSevice
              changeOrigin: true 
  getProjectPipeline:
    apiEndpoints:
      - getProject
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: projectSevice
              changeOrigin: true 
  getProjectKanbanPipeline:
    apiEndpoints:
      - getProjectKanban
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: projectSevice
              changeOrigin: true 
  getProjectScrumPipeline:
    apiEndpoints:
      - getProjectScrum
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: projectSevice
              changeOrigin: true 
  getProjectBugtrackingPipeline:
    apiEndpoints:
      - getProjectBugtracking
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: projectSevice
              changeOrigin: true 
  getAllUsersPipeline:
    apiEndpoints:
      - getAllUsers
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authSevice
              changeOrigin: true 
  getPriorityPipeline:
    apiEndpoints:
      - getPriority
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: prioritySevice
              changeOrigin: true 
  getComponentPipeline:
    apiEndpoints:
      - getComponent
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: componentSevice
              changeOrigin: true
  postComponentPipeline:
    apiEndpoints:
      - postComponent
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: componentSevice
              changeOrigin: true 
  updateComponentPipeline:
    apiEndpoints:
      - updateComponent
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: componentSevice
              changeOrigin: true 
  getIssueTypePipeline:
    apiEndpoints:
      - getIssue
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: issueSevice
              changeOrigin: true
  getLabelTypePipeline:
    apiEndpoints:
      - getLabel
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: labelSevice
              changeOrigin: true 
  getLinkedIssuesTypePipeline:
    apiEndpoints:
      - getLinkedIssues
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: linkedissuesSevice
              changeOrigin: true 
  getSprintTypePipeline:
    apiEndpoints:
      - getSprint
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sprintSevice
              changeOrigin: true 
  postSprintTypePipeline:
    apiEndpoints:
      - postSprint
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sprintSevice
              changeOrigin: true 
  updateSprintPipeline:
    apiEndpoints:
      - updateSprint
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sprintSevice
              changeOrigin: true
  postWorkItemPipeline:
    apiEndpoints:
      - postWorkItem
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true
  getWorkItemPipeline:
    apiEndpoints:
      - getWorkItem
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true 
  getWorkItemEpicPipeline:
    apiEndpoints:
      - getWorkItemEpic
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true 
  getWorkItemByIdPipeline:
    apiEndpoints:
      - getWorkItemById
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true 
  getIssueEpicPipeline:
    apiEndpoints:
      - getIssueEpic
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: issueSevice
              changeOrigin: true
  getWorkItemProjectPipeline:
    apiEndpoints:
      - getWorkItemProject
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true
  postCommentPipeline:
    apiEndpoints:
      - postComment
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: commentSevice
              changeOrigin: true 
  changeItemPositionPipeline:
    apiEndpoints:
      - changeItemPosition
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true
  putCommentPipeline:
    apiEndpoints:
      - putComment
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: commentSevice
              changeOrigin: true
  changeItemPositionBTSprintsPipeline:
    apiEndpoints:
      - changeItemPositionBTSprints
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true 
  workItemPositionStatusPipeline:
    apiEndpoints:
      - changeWorkItemPositionStatus
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true
  workItemStatusPipeline:
    apiEndpoints:
      - changeWorkItemStatus
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true
  updateWorkItemPipeline:
    apiEndpoints:
      - updateWorkItem
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: workItemSevice
              changeOrigin: true
  getComponentByProject:
    apiEndpoints:
      - getComponentByProject
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: componentSevice
              changeOrigin: true 
              